name: zakah
version: 0.0.4
authors:
- Komu Wairagu <https://www.komu.engineer/>
description: Zakah is safaricom's Mpesa client library.
homepage: https://github.com/komuw/zakah
environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'
# dependencies:
dev_dependencies:
  test: '>=1.0.0'

# pub publish --dry-run
# pub publish
