# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
        - image: ubuntu:16.04
    working_directory: ~/work
    steps:
        - checkout
        - run:
            name: install apt deps and dart
            command: |
                apt -y update
                apt -y install curl apt-transport-https
                sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
                sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_unstable.list > /etc/apt/sources.list.d/dart_unstable.list'
                apt -y update
                apt -y install \
                            curl \
                            wget \
                            git \
                            dart \
                            nano

        - run:
            name: add dart bin dir to path
            command: |
                echo "export PATH=$PATH:/usr/lib/dart/bin" >> /etc/profile
                echo "export LC_ALL=C.UTF-8" >> /etc/profile
                echo "export LANG=C.UTF-8" >> /etc/profile
                source /etc/profile

        - run:
            name: check dart and pub version
            command: |
                pwd
                ls -lha
                source /etc/profile && dart --version
                source /etc/profile && pub version

        - run:
            name: run tests and static analyzers;
            command: |
                source /etc/profile && dart format --fix --line-length 100 --set-exit-if-changed .
                source /etc/profile && dart fix --apply
                source /etc/profile && dart analyze --fatal-infos --fatal-warnings .
                # source /etc/profile && pub run test --timeout 10s --chain-stack-traces $(pwd)

  deploy:
    docker:
        - image: ubuntu:16.04
    working_directory: ~/work
    steps:
        - checkout
        - run:
            name: install apt deps and dart
            command: |
                apt -y update
                apt -y install curl apt-transport-https
                sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
                sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_unstable.list > /etc/apt/sources.list.d/dart_unstable.list'
                apt -y update
                apt -y install \
                            curl \
                            wget \
                            git \
                            dart \
                            nano

        - run:
            name: add dart bin dir to path
            command: |
                echo "export PATH=$PATH:/usr/lib/dart/bin" >> /etc/profile
                echo "export LC_ALL=C.UTF-8" >> /etc/profile
                echo "export LANG=C.UTF-8" >> /etc/profile
                source /etc/profile

        - run:
            name: do a new release
            command: |
                LAST_GIT_MESSAGE=$(git log -n1 --format=oneline --pretty=%B)
                echo "last git commit message on master:"
                echo $LAST_GIT_MESSAGE
                if [ "$LAST_GIT_MESSAGE" == 'do release' ]; then
                    echo "publishing to; https://pub.dartlang.org "
                    source /etc/profile && pub publish
                fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/